version: '3'

services:
  nginx:
    build:
      context: ./setup/nginx
      dockerfile: Dockerfile
    links:
      - rook-service:rook-service
      - tworavens:tworavens
    ports:
      - "8060:8060"
    depends_on:
      - tworavens
      - rook-service
  rook-service:
    build:
      context: ./
      dockerfile: Dockerfile-rook
    ports:
      - "8000"
  tworavens:
    build: ./Dockerfile
    links:
      - rook-service
    #command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080"
